# LINE Messaging API
YOUR_CHANNEL_ACCESS_TOKEN = 'チャネルアクセストークン'
YOUR_CHANNEL_SECRET = 'チャネルシークレット'

# messages
NEXT = 'NEXT'
NOTNEXT = 'NO PARTICIPANT'
MATCHED = 'MATCHED'

REMOVE = 'REMOVE'

REMOVED = 'REMOVED'

FAILED = 'FAILED'
